'use client';
import {useEffect,useState} from 'react';
import Image from 'next/image';
export function NSSLogo({size=48}:{size?:number}){return <Image src="/nss-logo.png" alt="National Service Scheme" width={size} height={size} className="nss-logo" unoptimized/>}
export function CollegeIdentity({settings:s}:any){return <div className="college-identity">{s.collegeLogo&&<Image unoptimized src={s.collegeLogo} alt={`${s.institution} logo`} width={40} height={40}/>}<span>{s.institution==='Your institution'?'NSS workspace':s.institution}</span></div>}
export function CollegeLogoField({initial}:any){const [value,setValue]=useState(initial||''),[error,setError]=useState('');return <div className="field wide"><label htmlFor="college-logo">College logo (shown only after sign-in)</label><input type="hidden" name="collegeLogo" value={value}/><input id="college-logo" type="file" accept="image/png,image/jpeg,image/webp" onChange={async e=>{const file=e.target.files?.[0];if(!file)return;setError('');if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>140*1024){setError('Choose a PNG, JPG or WebP under 140 KB.');e.target.value='';return;}const reader=new FileReader();reader.onload=()=>setValue(String(reader.result));reader.onerror=()=>setError('Could not read this image. Try another file.');reader.readAsDataURL(file);}}/>{value&&<div className="flex-row"><Image unoptimized src={value} alt="College logo preview" width={64} height={64} style={{objectFit:'contain'}}/><button type="button" className="btn small" onClick={()=>setValue('')}>Remove logo</button></div>}{error&&<small role="alert">{error}</small>}<small>Use your institution’s approved logo. This deployment serves one college; use separate deployments and databases for other colleges.</small></div>}
export function CategoryPicker({catalogs,initial}:any){const [value,setValue]=useState(initial||'');const rows=catalogs.filter((c:any)=>c.kind==='category');const selected=rows.find((c:any)=>c.name===value);let details:any={};try{details=JSON.parse(selected?.details||'{}')}catch{}return <div className="field"><label htmlFor="event-category">Category</label><select id="event-category" name="category" className="input" required value={value} onChange={e=>setValue(e.target.value)}><option value="" disabled>Select category</option>{!rows.some((c:any)=>c.name===value)&&value&&<option>{value}</option>}{['Regular activities','Special camping','Other'].map(group=><optgroup key={group} label={group}>{rows.filter((c:any)=>{try{return (JSON.parse(c.details||'{}').group||'Other')===group}catch{return group==='Other'}}).map((c:any)=><option key={c.id} value={c.name}>{c.name}</option>)}</optgroup>)}</select><small aria-live="polite">{details.description||'Choose the activity that best describes the event.'}</small><small>{details.group==='Special camping'?'Special camping: a 7-day residential community programme. Record daily attendance separately; hours require review.':'Regular activities: service throughout the year, normally 120 hours per year. Hours require review.'}</small></div>}
export function PhotoFields(){const [source,setSource]=useState('live');return <><div className="field"><label htmlFor="proof-source">Photo source</label><select id="proof-source" name="source" className="input" value={source} onChange={e=>setSource(e.target.value)}><option value="live">Camera or photo library</option><option value="geotag-app">Photo from a geotag camera app</option></select></div><label className="field"><span>{source==='geotag-app'?'Upload the original app-stamped photo':'Take or upload a photo'}</span><input name="file" type="file" required accept="image/jpeg,image/png,image/webp"/><small>JPG, PNG or WebP · up to 5 MB. Keep the location and time stamp visible.</small></label>{source==='geotag-app'&&<div className="field-grid"><label className="field"><span>Geotag app name</span><input name="captureApp" required maxLength={100} placeholder="Name of the app used"/></label><label className="field"><span>Capture date & time shown on photo</span><input name="captureTime" type="datetime-local" required/><small>Enter in this device’s local time zone.</small></label><label className="field"><span>Latitude shown on photo</span><input name="captureLat" type="number" required min={-90} max={90} step="any"/></label><label className="field"><span>Longitude shown on photo</span><input name="captureLng" type="number" required min={-180} max={180} step="any"/></label><p className="help-note wide">These details are your declaration, not verified GPS. Faculty will compare them with the visible stamp. Live upload GPS is recorded separately; denied GPS still allows submission for review.</p></div>}</>}
export function CaptureDetails({location:l}:any){const c=l.declaredCapture;return <div className="info-strip"><strong>{l.source==='geotag-app'?'Geotag-app photo':'Camera / library photo'}</strong>{c&&<><p>Declared app: {c.app}</p><p>Declared capture: {new Date(c.time).toLocaleString('en-IN')} · {c.lat}, {c.lng}</p><p>{c.distance} m from event (declared coordinates).</p><p>Unverified declaration: compare with the visible photo stamp. It does not replace check-in or upload GPS.</p></>}<small>The map below shows upload GPS, not the declared capture location.</small></div>}
export function HistoricalHours({data:d,request,save,parseCSV,busy}:any){
 const [student,setStudent]=useState(d.students[0]?.id||''),[year,setYear]=useState('1'),[history,setHistory]=useState<any[]>([]),[loaded,setLoaded]=useState(false),[error,setError]=useState(''),[hours,setHours]=useState('0'),[rows,setRows]=useState<any[]>([]),[bulk,setBulk]=useState(false),[attempt,setAttempt]=useState(0);
 useEffect(()=>{let live=true;setLoaded(false);setError('');if(!student)return;request('historical-hours?student='+encodeURIComponent(student)).then((r:any)=>{if(live){setHistory(r.rows);setLoaded(true)}}).catch((e:any)=>{if(live)setError(e.message)});return()=>{live=false}},[student,request,attempt]);
 const latest=history.find((r:any)=>r.year===Number(year));
 useEffect(()=>{setHours(String(latest?.balance||0))},[latest?.id,student,year]);
 const canEdit=d.historical.canEdit;
 return <form className="form-stack" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const s=d.students.find((s:any)=>s.id===student);save({reason:f.get('reason'),source:f.get('source'),rows:bulk?rows:[{nss_id:s?.nss_id,year:Number(year),hours,revision:latest?.revision||0}]})}}>
 <div className="info-strip"><strong>Service completed through 6 October 2026</strong><p>Enter only verified service hours that are missing from SevaTrack. This sets a historical total for each year; it does not add that amount again on repeat submissions.</p><p>Faculty entry closes at midnight after 7 October 2026, India time. Administrators can correct balances afterward.</p></div>
 {canEdit&&<label className="check-row"><input type="checkbox" checked={bulk} onChange={e=>{setBulk(e.target.checked);setError('')}}/>Import multiple students from CSV</label>}
 {bulk?<><a className="btn" href="/api/historical-template">Download current balances / CSV template</a><p className="help-note">Edit hours only, keep NSS ID, year and revision. Import at most 200 rows; split larger files. Unchanged balances are skipped. All rows are validated before saving.</p><label className="field"><span>Historical hours CSV</span><input type="file" accept=".csv,text/csv" required onChange={async e=>{setRows([]);setError('');try{const f=e.target.files?.[0];if(!f)return;if(f.size>200000)throw new Error('CSV must be under 200 KB.');const parsed=parseCSV(await f.text()),header=parsed.shift()||[];if(!['nss_id','year','hours','revision'].every(k=>header.includes(k))||new Set(header).size!==header.length)throw new Error('Use the downloaded template, including revision.');const rr=parsed.filter((r:string[])=>r.some(Boolean)).map((r:string[])=>Object.fromEntries(header.map((k:string,i:number)=>[k,r[i]||''])));if(!rr.length||rr.length>200)throw new Error('Select 1–200 rows.');setRows(rr)}catch(e:any){setError(e.message)}}}/></label>{rows.length>0&&<div className="table-wrap" tabIndex={0} aria-label="Import preview"><table><thead><tr><th>NSS ID</th><th>Year</th><th>Historical total</th></tr></thead><tbody>{rows.slice(0,10).map((r,i)=><tr key={i}><td>{r.nss_id}</td><td>{r.year}</td><td>{r.hours}h</td></tr>)}</tbody></table><p>{rows.length} rows ready · first 10 shown</p></div>}</>:<><label className="field"><span>Student</span><select className="input" value={student} onChange={e=>setStudent(e.target.value)}>{d.students.map((s:any)=><option value={s.id} key={s.id}>{s.name} · {s.nss_id}</option>)}</select></label><label className="field"><span>NSS year</span><select className="input" value={year} onChange={e=>setYear(e.target.value)}><option value="1">Year 1</option><option value="2">Year 2</option></select></label>{!loaded&&!error&&<p role="status">Loading historical records…</p>}{canEdit&&<label className="field"><span>Total historical hours for this year</span><input type="number" min={0} max={1000} step="0.01" required value={hours} onChange={e=>setHours(e.target.value)}/></label>}<div aria-label="Historical hour changes">{history.filter(h=>h.year===Number(year)).map(h=><div className="info-strip" key={h.id}><strong>{h.balance}h total ({h.delta>=0?'+':''}{h.delta}h correction)</strong><p>{h.reason} · Source: {h.source}</p><small>{h.actor_name} · {new Date(h.created_at).toLocaleString('en-IN')} · Revision {h.revision}</small></div>)}{loaded&&!history.some(h=>h.year===Number(year))&&<p>No historical hours recorded for this year.</p>}</div></>}
 {error&&<div role="alert">{error}{!bulk&&<button type="button" className="btn" onClick={()=>setAttempt(x=>x+1)}>Retry</button>}</div>}
 {canEdit?<><label className="field"><span>Supporting logbook / record reference</span><input name="source" required maxLength={500}/></label><label className="field"><span>Reason for entry or correction</span><textarea name="reason" required maxLength={1000}/></label><label className="check-row"><input type="checkbox" required/>I verified these hours and excluded service already recorded in attendance.</label><button className="btn primary" type="submit" disabled={busy||!!error||(bulk?!rows.length:!loaded)}>{busy?'Saving…':'Save historical balances'}</button></>:<p>Read-only after the faculty cutoff. Ask an administrator to make corrections.</p>}
 </form>
}
