import {all,one} from './db';
import {AppError} from './errors';
export function scope(u:any){return u.role==='STUDENT'?{where:'a.user_id=?',args:[u.id]}:u.role==='FACULTY'?{where:'e.coordinator=?',args:[u.id]}:{where:'1=1',args:[]}}
export const attendanceSelect=`SELECT a.*,e.title event_title,e.proof proof_required,e.start event_start,e.location event_location,u.name student_name,u.nss_id,u.roll,u.department,u.batch,ROUND(COALESCE((SELECT SUM(delta) FROM hour_ledger l WHERE l.attendance_id=a.id),0),2) approved_hours,(SELECT COUNT(*) FROM evidence p WHERE p.attendance_id=a.id) proof_count,(SELECT COUNT(*) FROM evidence p WHERE p.attendance_id=a.id AND p.status='PENDING') pending_proof FROM attendance a JOIN events e ON e.id=a.event_id JOIN users u ON u.id=a.user_id`;
export async function records(u:any,p:URLSearchParams,complete=false){const kind=p.get('kind')||'attendance',q=(p.get('q')||'').slice(0,150),status=p.get('status')||'all',eid=p.get('event')||'',page=Math.max(1,Math.floor(Number(p.get('page'))||1)),size=Math.min(50,Math.max(10,Math.floor(Number(p.get('size'))||25))),sort=p.get('sort')||'date',dir=p.get('dir')==='asc'?'ASC':'DESC';let sc=scope(u),where=sc.where,args:any[]=[...sc.args],select=attendanceSelect,keys:any={date:'a.created_at',name:'u.name',event:'e.title',status:'a.status',hours:'approved_hours'},extra='';
 if(kind==='attendance'){if(q){where+=' AND (u.name LIKE ? OR u.nss_id LIKE ? OR u.roll LIKE ? OR e.title LIKE ?)';args.push(...Array(4).fill('%'+q+'%'))}if(status!=='all'){if(status==='pending'){where+=" AND a.status IN ('PENDING_REVIEW','CHECKED_OUT','EVIDENCE_PENDING')"}else{where+=' AND a.status=?';args.push(status)}}if(eid){where+=' AND e.id=?';args.push(eid)}if(p.get('student')){where+=' AND a.user_id=?';args.push(p.get('student'))}}
 else if(kind==='notifications'){where='a.user_id=?';args=[u.id];select='SELECT a.* FROM notifications a';keys={date:'a.created_at',name:'a.title'};if(q){where+=' AND (a.title LIKE ? OR a.body LIKE ?)';args.push('%'+q+'%','%'+q+'%')}if(status==='unread')where+=' AND a.read=0'}
 else if(kind==='evidence'||kind==='corrections'){const isPhoto=kind==='evidence';select=isPhoto?`SELECT p.*,u.name student_name,e.title event_title,e.lat event_lat,e.lng event_lng,e.radius FROM evidence p JOIN attendance a ON a.id=p.attendance_id JOIN events e ON e.id=a.event_id JOIN users u ON u.id=a.user_id`:`SELECT p.*,u.name student_name,e.title event_title FROM corrections p JOIN attendance a ON a.id=p.attendance_id JOIN events e ON e.id=a.event_id JOIN users u ON u.id=a.user_id`;keys={date:'p.created_at',name:'u.name'};where+=isPhoto?" AND p.status IN ('PENDING','CLARIFICATION')":" AND p.status='PENDING'";if(q){where+=' AND (u.name LIKE ? OR e.title LIKE ?)';args.push('%'+q+'%','%'+q+'%')}}
 else if(kind==='history'){select=`SELECT l.*,e.title event_title,u.name actor_name FROM hour_ledger l JOIN attendance a ON a.id=l.attendance_id JOIN events e ON e.id=a.event_id LEFT JOIN users u ON u.id=l.actor`;keys={date:'l.created_at',name:'e.title',hours:'l.delta'};if(q){where+=' AND (e.title LIKE ? OR l.reason LIKE ?)';args.push('%'+q+'%','%'+q+'%')}if(p.get('year')){where+=' AND l.year=?';args.push(Number(p.get('year')))}}
 else if(kind==='events'){where=u.role==='FACULTY'?'e.coordinator=?':"e.status!='Draft'";args=u.role==='FACULTY'?[u.id]:[];if(u.role==='ADMIN')where='1=1';select=`SELECT e.*,u.name coordinator_name,(SELECT COUNT(*) FROM attendance a WHERE a.event_id=e.id AND a.status!='CANCELLED') registrations FROM events e JOIN users u ON u.id=e.coordinator`;keys={date:'e.start',name:'e.title',status:'e.status'};if(q){where+=' AND (e.title LIKE ? OR e.location LIKE ? OR e.category LIKE ?)';args.push(...Array(3).fill('%'+q+'%'))}if(status==='upcoming')where+=" AND e.status NOT IN ('Draft','Completed','Cancelled') AND e.end>=strftime('%Y-%m-%dT%H:%M:%fZ','now')";else if(status==='past')where+=" AND (e.status IN ('Completed','Cancelled') OR e.end<strftime('%Y-%m-%dT%H:%M:%fZ','now'))";else if(status==='draft'){if(u.role==='STUDENT')throw new AppError('Draft events are restricted.',403);where+=" AND e.status='Draft'"}}
 else if(kind==='reports'){if(u.role==='STUDENT')throw new AppError('This report is restricted.',403);where=u.role==='FACULTY'?'e.coordinator=?':'1=1';args=u.role==='FACULTY'?[u.id]:[];select=`SELECT e.id,e.title,e.start,COUNT(a.id) registrations,SUM(CASE WHEN a.status IN ('APPROVED','PARTIAL') THEN 1 ELSE 0 END) approved,SUM(CASE WHEN a.status='ABSENT' THEN 1 ELSE 0 END) absent,ROUND(COALESCE((SELECT SUM(l.delta) FROM hour_ledger l JOIN attendance aa ON aa.id=l.attendance_id WHERE aa.event_id=e.id),0),2) hours FROM events e LEFT JOIN attendance a ON a.event_id=e.id AND a.status!='CANCELLED'`;extra=' GROUP BY e.id';keys={date:'e.start',name:'e.title',hours:'hours'};if(q){where+=' AND e.title LIKE ?';args.push('%'+q+'%')}}
 else if(kind==='audit'){if(u.role!=='ADMIN')throw new AppError('Audit access is restricted.',403);where='1=1';args=[];select='SELECT a.*,u.name actor_name FROM audit_logs a LEFT JOIN users u ON u.id=a.actor';keys={date:'a.created_at',name:'u.name'};if(q){where+=' AND (a.action LIKE ? OR a.reason LIKE ? OR u.name LIKE ?)';args.push(...Array(3).fill('%'+q+'%'))}}
 else throw new AppError('Unknown records collection.');
 const base=`${select} WHERE ${where}${extra}`;const count=await one(`SELECT COUNT(*) total FROM (${base})`,...args);const maxPage=Math.max(1,Math.ceil(count.total/size)),current=Math.min(page,maxPage);const rows=await all(`${base} ORDER BY ${keys[sort]||Object.values(keys)[0]} ${dir},${kind==='events'||kind==='reports'?'e.id':kind==='history'?'l.id':['evidence','corrections'].includes(kind)?'p.id':'a.id'} ASC ${complete?'':'LIMIT ? OFFSET ?'}`, ...args,...(complete?[]:[size,(current-1)*size]));return {rows,total:count.total,page:current,size,pages:maxPage};}
export async function summaries(u:any){const sc=scope(u);const counts=await one(`SELECT COUNT(*) attendance_count,COALESCE(SUM(a.status IN ('PENDING_REVIEW','EVIDENCE_PENDING','CHECKED_OUT')),0) pending,COALESCE(SUM(a.status IN ('APPROVED','PARTIAL')),0) completed,COUNT(DISTINCT CASE WHEN a.status IN ('APPROVED','PARTIAL') THEN a.event_id END) participated_events FROM attendance a JOIN events e ON e.id=a.event_id WHERE ${sc.where}`,...sc.args);const balance=await one(`SELECT ROUND(COALESCE(SUM(l.delta),0),2) hours FROM hour_ledger l JOIN attendance a ON a.id=l.attendance_id JOIN events e ON e.id=a.event_id WHERE ${sc.where}`,...sc.args);const monthly=await all(`SELECT substr(l.created_at,1,7) month,ROUND(SUM(l.delta),2) hours FROM hour_ledger l JOIN attendance a ON a.id=l.attendance_id JOIN events e ON e.id=a.event_id WHERE ${sc.where} AND l.created_at>=datetime('now','-6 months') GROUP BY substr(l.created_at,1,7)`,...sc.args);const proofs=await one(`SELECT COUNT(*) total FROM evidence p JOIN attendance a ON a.id=p.attendance_id JOIN events e ON e.id=a.event_id WHERE ${sc.where} AND p.status IN ('PENDING','CLARIFICATION')`,...sc.args);const unread=await one('SELECT COUNT(*) total FROM notifications WHERE user_id=? AND read=0',u.id);const corrections=await one(`SELECT COUNT(*) total FROM corrections c JOIN attendance a ON a.id=c.attendance_id JOIN events e ON e.id=a.event_id WHERE ${sc.where} AND c.status='PENDING'`,...sc.args);const next=u.role==='STUDENT'?await one(attendanceSelect+` WHERE a.user_id=? AND (a.status='CHECKED_IN' OR (a.status='REGISTERED' AND e.end>=strftime('%Y-%m-%dT%H:%M:%fZ','now'))) ORDER BY CASE WHEN a.status='CHECKED_IN' THEN 0 ELSE 1 END,e.start LIMIT 1`,u.id):null;const latest=u.role==='STUDENT'?await one(attendanceSelect+` WHERE a.user_id=? AND a.status IN ('APPROVED','PARTIAL','REJECTED','ABSENT') ORDER BY (SELECT MAX(created_at) FROM adjustments x WHERE x.attendance_id=a.id) DESC LIMIT 1`,u.id):null;return {counts:{...counts,hours:balance.hours,proofs:proofs.total,unread:unread.total,corrections:corrections.total},monthly,next,latest};}
